Repository OSCA-Ado-Ekiti/Hacktoberfest2023-Ekiti, pull requests merged in 2023-10, with the labels that each got.

#1 add my details
  participants.json
Labels: hacktoberfest-accepted

#2 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#4 i added my details
  participants.json
Labels: hacktoberfest, hacktoberfest-accepted

#5 Update participants.json
  participants.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#6 add: new details
  participants.json
Labels: hacktoberfest, hacktoberfest-accepted

#8 feat:added name to participant.json
  participants.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#7 name added
  participants.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#9 Update participants.json
  participants.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#10 Added Maloney to participants.json
  participants.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#11 Update participants.json
  participants.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#12 favour's profile
  participants.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#13 Added myself to participants
  participants.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#14 Added my info to the participants
  participants.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#15 Update participants.json
  participants.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#19 Update participants.json
  participants.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#18 fixed
  participants.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#20 Abdulsamad
  participants.json
Labels: hacktoberfest-accepted

#21 add-my-details
  participants.json
Labels: hacktoberfest-accepted
